-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["upvote"] = {
                                
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12, -13.5  ,  9, -16.5  ,  12, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, -13.5  ,  -12, -13.5  ,  13, -9.5  ,  8, -5.5  ,  -15, -5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2, -32.5  ,  3, -26.5  ,  -2, -29.5  ,  -2, -32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, -5.5  ,  13, -9.5  ,  15, -10.5  ,  15, -5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10, -16.5  ,  13, -9.5  ,  -12, -13.5  ,  -12, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -23.5  ,  13, -9.5  ,  -8, -20.5  ,  -8, -23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, -29.5  ,  3, -26.5  ,  -4, -26.5  ,  -4, -29.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -23.5  ,  -6, -23.5  ,  -4, -26.5  ,  5, -26.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4, -26.5  ,  -6, -23.5  ,  -6, -25.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -9.5  ,  12, -13.5  ,  14, -13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, -20.5  ,  13, -9.5  ,  -10, -16.5  ,  -10, -19.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 32.5  ,  -8, -5.5  ,  8, -5.5  ,  8, 32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9, -20.5  ,  9, -16.5  ,  5, -23.5  ,  7, -23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -9.5  ,  9, -16.5  ,  12, -13.5  }
                    }
                    
		}
		
		, 
		["downvote"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12, 9.5  ,  7, 6.5  ,  15, 6.5  ,  15, 9.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, 10.5  ,  -7, 6.5  ,  -11, 12.5  ,  -13, 12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, 12.5  ,  7, 6.5  ,  12, 9.5  ,  13, 12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, 22.5  ,  -9, 16.5  ,  7, 19.5  ,  7, 22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7, 19.5  ,  -5, 22.5  ,  -7, 22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -9, 16.5  ,  -7, 19.5  ,  -9, 19.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1, 32.5  ,  -1, 28.5  ,  1, 28.5  ,  1, 32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -11, 12.5  ,  -7, 6.5  ,  7, 6.5  ,  11, 12.5  ,  11, 15.5  ,  7, 19.5  ,  -9, 16.5  ,  -11, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, 6.5  ,  -7, 6.5  ,  -13, 10.5  ,  -15, 9.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 28.5  ,  -5, 22.5  ,  -9, 16.5  ,  5, 22.5  ,  4, 28.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5, 22.5  ,  1, 28.5  ,  -4, 28.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "downvote", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, -32.5  ,  7, 6.5  ,  -7, 6.5  ,  -7, -32.5  }
                    }
                    
                    
                    
		}
		
		, 
		["gold"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "gold", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 14.000
                    }
                    
                    
		}
		
		, 
		["snoo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12, -46.5  ,  8, -42.5  ,  7, -42.5  ,  7, -47.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, -42.5  ,  8, -39.5  ,  3, -39.5  ,  2, -43.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, -42.5  ,  12, -46.5  ,  13, -46.5  ,  13, -42.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, -42.5  ,  8, -42.5  ,  8, -39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, -39.5  ,  13, -46.5  ,  18, -50.5  ,  35, -46.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -46.5  ,  12, -46.5  ,  18, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, 4.5  ,  -39, 0.5  ,  39, 0.5  ,  39, 4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23, -31.5  ,  -43, 0.5  ,  -44, -32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                   -- filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, -39.5  ,  3, -36.5  ,  -3, -35.5  ,  -3, -39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, 0.5  ,  24, -33.5  ,  44, -32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, 33.5  ,  -23, 37.5  ,  -33, 38.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   34, 44.5  ,  24, 39.5  ,  34, 39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23, 39.5  ,  -34, 44.5  ,  -33, 39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38, 53.5  ,  34, 44.5  ,  38, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -34, 44.5  ,  -38, 53.5  ,  -38, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, 39.5  ,  -23, 39.5  ,  24, 36.5  ,  33, 37.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23, 39.5  ,  24, 39.5  ,  34, 44.5  ,  38, 53.5  ,  -38, 53.5  ,  -34, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, 36.5  ,  33, 33.5  ,  33, 36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                   -- filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3, -35.5  ,  -23, -31.5  ,  -24, -36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, -36.5  ,  43, 0.5  ,  -43, 0.5  ,  -23, -31.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, 7.5  ,  -33, 33.5  ,  -39, 34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, 7.5  ,  -33, 7.5  ,  -23, 37.5  ,  -33, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 33.5  ,  38, 7.5  ,  38, 34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, 36.5  ,  -23, 39.5  ,  34, 7.5  ,  38, 7.5  ,  33, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, -33.5  ,  3, -36.5  ,  23, -36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, 0.5  ,  3, -36.5  ,  24, -33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                   -- filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23, 39.5  ,  -23, 37.5  ,  34, 4.5  ,  34, 7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "snoo", density = 2, friction = 0, bounce = 0, 
                    --filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, 4.5  ,  34, 4.5  ,  -23, 37.5  ,  -33, 7.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

